[2022-10-01 18:11:20,708] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: data_cleaning_dag.cleaned_data_message manual__2022-10-01T18:11:09.504243+00:00 [queued]>
[2022-10-01 18:11:20,724] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: data_cleaning_dag.cleaned_data_message manual__2022-10-01T18:11:09.504243+00:00 [queued]>
[2022-10-01 18:11:20,726] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-10-01 18:11:20,726] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-10-01 18:11:20,727] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-10-01 18:11:20,751] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): cleaned_data_message> on 2022-10-01 18:11:09.504243+00:00
[2022-10-01 18:11:20,759] {standard_task_runner.py:52} INFO - Started process 1865 to run task
[2022-10-01 18:11:20,765] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'data_cleaning_dag', 'cleaned_data_message', 'manual__2022-10-01T18:11:09.504243+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/data_cleaning_dag/data_cleaning.py', '--cfg-path', '/tmp/tmpnrz7881c', '--error-file', '/tmp/tmpciz9u6cs']
[2022-10-01 18:11:20,768] {standard_task_runner.py:80} INFO - Job 9: Subtask cleaned_data_message
[2022-10-01 18:11:20,885] {task_command.py:371} INFO - Running <TaskInstance: data_cleaning_dag.cleaned_data_message manual__2022-10-01T18:11:09.504243+00:00 [running]> on host 408deac6c455
[2022-10-01 18:11:21,008] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_cleaning_dag
AIRFLOW_CTX_TASK_ID=cleaned_data_message
AIRFLOW_CTX_EXECUTION_DATE=2022-10-01T18:11:09.504243+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-10-01T18:11:09.504243+00:00
[2022-10-01 18:11:21,011] {logging_mixin.py:115} INFO - Data successfully cleaned
[2022-10-01 18:11:21,012] {python.py:173} INFO - Done. Returned value was: None
[2022-10-01 18:11:21,039] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=data_cleaning_dag, task_id=cleaned_data_message, execution_date=20221001T181109, start_date=20221001T181120, end_date=20221001T181121
[2022-10-01 18:11:21,097] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-10-01 18:11:21,158] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
