[2022-10-01 18:17:15,893] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: data_cleaning_dag.data_cleaning manual__2022-10-01T18:11:09.504243+00:00 [queued]>
[2022-10-01 18:17:15,918] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: data_cleaning_dag.data_cleaning manual__2022-10-01T18:11:09.504243+00:00 [queued]>
[2022-10-01 18:17:15,919] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-10-01 18:17:15,920] {taskinstance.py:1377} INFO - Starting attempt 2 of 2
[2022-10-01 18:17:15,921] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-10-01 18:17:15,954] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): data_cleaning> on 2022-10-01 18:11:09.504243+00:00
[2022-10-01 18:17:15,964] {standard_task_runner.py:52} INFO - Started process 2113 to run task
[2022-10-01 18:17:15,970] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'data_cleaning_dag', 'data_cleaning', 'manual__2022-10-01T18:11:09.504243+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/data_cleaning_dag/data_cleaning.py', '--cfg-path', '/tmp/tmpxks11eoq', '--error-file', '/tmp/tmpeecnk4l5']
[2022-10-01 18:17:15,974] {standard_task_runner.py:80} INFO - Job 10: Subtask data_cleaning
[2022-10-01 18:17:16,141] {task_command.py:371} INFO - Running <TaskInstance: data_cleaning_dag.data_cleaning manual__2022-10-01T18:11:09.504243+00:00 [running]> on host 408deac6c455
[2022-10-01 18:17:16,288] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_cleaning_dag
AIRFLOW_CTX_TASK_ID=data_cleaning
AIRFLOW_CTX_EXECUTION_DATE=2022-10-01T18:11:09.504243+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-10-01T18:11:09.504243+00:00
[2022-10-01 18:17:21,560] {python.py:173} INFO - Done. Returned value was: None
[2022-10-01 18:17:21,608] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=data_cleaning_dag, task_id=data_cleaning, execution_date=20221001T181109, start_date=20221001T181715, end_date=20221001T181721
[2022-10-01 18:17:21,688] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-10-01 18:17:21,768] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
